# Generated by Django 5.2.7 on 2025-11-02 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('P', 'Prefer not to say')], max_length=1)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('language_preference', models.CharField(default='en', max_length=10)),
                ('notification_preferences', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'profiles_user_profile',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalAffiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=255)),
                ('affiliation_type', models.CharField(choices=[('HOSPITAL', 'Hospital'), ('CLINIC', 'Clinic'), ('UNIVERSITY', 'University'), ('RESEARCH', 'Research Institute'), ('PRIVATE', 'Private Practice'), ('OTHER', 'Other')], max_length=20)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_current', models.BooleanField(default=True)),
                ('verification_status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='profiles.userprofile')),
            ],
            options={
                'db_table': 'profiles_professional_affiliation',
            },
        ),
        migrations.CreateModel(
            name='EducationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(choices=[('MD', 'Doctor of Medicine'), ('DO', 'Doctor of Osteopathic Medicine'), ('MBBS', 'Bachelor of Medicine, Bachelor of Surgery'), ('OTHER', 'Other')], max_length=50)),
                ('institution', models.CharField(max_length=255)),
                ('field_of_study', models.CharField(max_length=255)),
                ('graduation_date', models.DateField()),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('honors', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_history', to='profiles.userprofile')),
            ],
            options={
                'db_table': 'profiles_education_history',
                'ordering': ['-graduation_date'],
            },
        ),
        migrations.CreateModel(
            name='DeviceSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255, unique=True)),
                ('device_type', models.CharField(choices=[('WEB', 'Web'), ('ANDROID', 'Android'), ('IOS', 'iOS'), ('TABLET', 'Tablet')], max_length=20)),
                ('device_name', models.CharField(max_length=255)),
                ('os_version', models.CharField(blank=True, max_length=50)),
                ('app_version', models.CharField(blank=True, max_length=50)),
                ('last_sync', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='profiles.userprofile')),
            ],
            options={
                'db_table': 'profiles_device_sync',
            },
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['user'], name='profiles_us_user_id_04ef0b_idx'),
        ),
        migrations.AddIndex(
            model_name='professionalaffiliation',
            index=models.Index(fields=['user_profile', 'is_current'], name='profiles_pr_user_pr_16e20b_idx'),
        ),
        migrations.AddIndex(
            model_name='professionalaffiliation',
            index=models.Index(fields=['verification_status'], name='profiles_pr_verific_3e1a2c_idx'),
        ),
        migrations.AddIndex(
            model_name='educationhistory',
            index=models.Index(fields=['user_profile'], name='profiles_ed_user_pr_ad7169_idx'),
        ),
        migrations.AddIndex(
            model_name='devicesync',
            index=models.Index(fields=['user_profile', 'is_active'], name='profiles_de_user_pr_d05549_idx'),
        ),
        migrations.AddIndex(
            model_name='devicesync',
            index=models.Index(fields=['device_id'], name='profiles_de_device__782128_idx'),
        ),
    ]
