# Generated by Django 5.2.7 on 2025-11-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='notification_preferences',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='institution',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('PHYSICIAN', 'Physician'), ('STAFF', 'Staff'), ('STUDENT', 'Student'), ('OTHER', 'Other')], default='OTHER', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='specialty',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='target_certification_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
