# Generated by Django 5.2.7 on 2025-11-03 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_userprofile_notification_preferences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='has_taken_exam',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='level',
            field=models.CharField(blank=True, choices=[('FELLOW', 'Fellow'), ('RESIDENT', 'Resident'), ('PHYSICIAN', 'Physician'), ('OTHER', 'Other')], default='OTHER', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='number_of_exams_taken',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('EXAMINER', 'Examiner'), ('ADMIN', 'Admin'), ('STAFF', 'Staff'), ('STUDENT', 'Student')], default='STUDENT', max_length=100),
        ),
    ]
