# Generated by Django 5.2.8 on 2025-11-18 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_has_taken_exam_userprofile_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='send_study_reminders',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='week_study_target_mins',
            field=models.PositiveBigIntegerField(blank=True, help_text='Minutes expected to spend on studying per week', null=True),
        ),
    ]
