# Generated by Django 5.2.8 on 2025-11-23 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_userprofile_send_study_reminders_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='has_taken_exam',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='level',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='number_of_exams_taken',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='send_study_reminders',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='target_certification_date',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='week_study_target_mins',
        ),
    ]
