# Generated by Django 5.2.8 on 2025-11-23 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_userprofile_has_taken_exam_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='specialty',
        ),
    ]
